_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_mixunet.yml',
  '_base_/yolov3_readermix.yml',
]

snapshot_epoch: 5
weights: output/yolov3_mobilenet_v1_270e_coco/model_final
